### ISSUE TITLE
about 1/10 data in mouth_roi_train is lost

### ISSUE THREAD

**Issue by wxystudio** [facebookresearch/VisualVoice#10]
I think the number of files in mp4, audio, mouth_roi_train is identity.
when I check it, there are 1092003 videos in mp4/train and audio/train, but 84730 of which are lost in mouth_roi/train. There is no  .h5 file of the same name in mouth_roi/train, such as:

video_path: mp4/train/id04262/96JSsr9Q00k/00009.mp4
mouthroi_path: mouth_roi/train/id04262/96JSsr9Q00k/00009.h5
audio_path: audio/train/id04262/96JSsr9Q00k/00009.wav

video_path: mp4/train/id04262/PX8fGdzDlEs/00011.mp4
mouthroi_path: mouth_roi/train/id04262/PX8fGdzDlEs/00011.h5
audio_path: audio/train/id04262/PX8fGdzDlEs/00011.wav

**Comment by wxystudio** [comment]
I see, the lost data is in seen and unseen directories

**Comment by wxystudio** [comment]
Sorry I re-check it and find that there are even 285 lost data in train set, the total number of video and audio train set data is 1092009, the number of mouth train set data is 1007279, the number of mouth seen_heard_test set data is 84445, but there are 285 data can't be found anywhere.
    Could you help me with it? or do you just ignore them?

**Comment by wxystudio** [comment]
my problem, sorry

**Comment by dengyuanjie** [comment]
I also found 285 H5 files missing when I processed the data. How do you solve the problem？ @wxystudio

**Comment by dengyuanjie** [comment]
I have met the same question. Could you share how you solved the problem? @wxystudio
