### ISSUE TITLE
how to separate the audio and mp4 directory

### ISSUE THREAD

**Issue by wxystudio** [facebookresearch/VisualVoice#2]
the mouth_roi dataset is separated by train,val,seen,unseen 4 directories, but the audio and mp4 raw dataset only contain train and test directory. So how to extract the seen and unseen dataset from raw dataset? thx very much

**Comment by rhgao** [comment]
You can download the hdf5 files that contain the data paths, then match the video ID to separate the seen and unseen test videos.

wget http://dl.fbaipublicfiles.com/VisualVoice/hdf5/VoxCeleb2/train.h5
wget http://dl.fbaipublicfiles.com/VisualVoice/hdf5/VoxCeleb2/val.h5
wget http://dl.fbaipublicfiles.com/VisualVoice/hdf5/VoxCeleb2/seen_heard_test.h5
wget http://dl.fbaipublicfiles.com/VisualVoice/hdf5/VoxCeleb2/unseen_unheard_test.h5
